name: Test Relay 
on: 
  pull_request:
    paths:
      - 'relays.yaml'

jobs:
  check_relay:
    name: Check 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            +(src|__tests__)/**/*.ts
            !src/exclude.ts
          FILES: |
            relays.yml
      - name: Check differences
        run: echo ${{ env.GIT_DIFF }}